// pages/(react)/layouts/LayoutDefault.tsx
import "./style.css";

import "./tailwind.css";
import type React from "react";
import logoUrl from "../../../assets/logo.svg";
import { Link } from "../../../components/Link.jsx";

export default function LayoutDefault({
	children,
}: { children: React.ReactNode }) {
	return (
		<div className="flex max-w-5xl m-auto">
			<Sidebar>
				<Logo />
				<Link href="/">Welcome [React]</Link>
				<Link href="/hello-vue">Hello Vue [Vue]</Link>
			</Sidebar>
			<Content>{children}</Content>
		</div>
	);
}

function Sidebar({ children }: { children: React.ReactNode }) {
	return (
		<div
			id="sidebar"
			className="p-5 flex flex-col shrink-0 border-r-2 border-r-gray-200"
		>
			{children}
		</div>
	);
}

function Content({ children }: { children: React.ReactNode }) {
	return (
		<div id="page-container">
			<div id="page-content" className="p-5 pb-12 min-h-screen">
				{children}
			</div>
		</div>
	);
}

function Logo() {
	return (
		<div className="p-5 mb-2">
			<a href="/">
				<img src={logoUrl} height={64} width={64} alt="logo" />
			</a>
		</div>
	);
}

// pages/vue/layouts/LayoutDefault.vue
<template>
  <div class="layout">
    <Sidebar>
      <Logo />
      <Link href="/"> Welcome [React]</Link>
      <Link href="/hello-vue"> Hello Vue [Vue] </Link>
    </Sidebar>
    <Content><slot /></Content>
  </div>
</template>

<script lang="ts" setup>
import Content from "../../../components/Content.vue";
import Link from "../../../components/Link.vue";
import Logo from "../../../components/Logo.vue";
import Sidebar from "../../../components/Sidebar.vue";
</script>

<style>
/* see https://stackoverflow.com/questions/55206901/how-to-import-css-files-in-vue-3-child-components */
@import "./tailwind.css";

body {
  margin: 0;
  font-family: sans-serif;
}
* {
  box-sizing: border-box;
}
a {
  text-decoration: none;
}
</style>

<style scoped>
.layout {
  display: flex;
  max-width: 900px;
  margin: auto;
}
.content {
  padding: 20px;
  padding-bottom: 50px;
  min-height: 100vh;
  flex-grow: 1;
}
/* Page Transition Animation */
#page-content {
  opacity: 1;
  transition: opacity 0.3s ease-in-out;
}
body.page-is-transitioning #page-content {
  opacity: 0;
}
</style>
